"""Remove internal id

Revision ID: e18983641cf5
Revises: a708763afe5f
Create Date: 2023-04-16 16:59:17.418959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e18983641cf5'
down_revision = 'a708763afe5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('internal_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
